# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

email: office@studioapt.co

description: > # this means to ignore newlines until "baseurl:"
  Studio Apartment is an independent design studio specializing in brand identity and interface design. We help people say what they’re trying to say, better. We do this by combining user-centered functional design principles with the visual arts.

baseurl: "" # the subpath of your site, e.g. /blog

# url: "https://www.studioapt.co"
url: "https://staging.jaredsalzano.com/studioapt"

headerText: 'Brooklyn, NY 11217'

social_media_links:
  - class: icon dribbble
    href: https://dribbble.com/gagesalzano
    svg: <svg width="21" height="21" viewBox="0 0 17 17"><path d="M13.462 3.774c-.146.2-1.306 1.702-3.865 2.757a21.648 21.648 0 0 1 .608 1.373c2.304-.292 4.592.177 4.82.225a7 7 0 0 0-1.563-4.355M6.482 1.4A37.39 37.39 0 0 1 9.065 5.49c2.461-.931 3.503-2.346 3.628-2.525a6.855 6.855 0 0 0-6.211-1.567M1.328 6.764c.31.004 3.162.016 6.4-.852A44.668 44.668 0 0 0 5.16 1.869a7.005 7.005 0 0 0-3.833 4.895m1.633 6.106c.157-.271 2.057-3.448 5.627-4.613.09-.03.181-.058.273-.084A23.598 23.598 0 0 0 8.3 6.987c-3.457 1.045-6.812 1.001-7.114.995a7.002 7.002 0 0 0 1.776 4.888m7.846 1.761c-.103-.613-.505-2.751-1.477-5.302l-.045.016c-3.905 1.374-5.306 4.109-5.43 4.366a6.845 6.845 0 0 0 6.952.92m4.13-5.326c-.236-.075-2.142-.65-4.311-.299.905 2.513 1.274 4.56 1.345 4.985a7.01 7.01 0 0 0 2.967-4.686M8.104 16.37C3.636 16.37 0 12.698 0 8.185S3.636 0 8.104 0c4.469 0 8.104 3.672 8.104 8.185s-3.635 8.185-8.104 8.185" fill="#4D4545" fill-rule="evenodd"/></svg>
  - class: icon twitter
    href: https://twitter.com/gagesalzano
    svg: <svg width="22.5" height="18.5" viewBox="0 0 18 15"><path d="M5.66 14.775c6.794 0 10.508-5.684 10.508-10.613 0-.161-.003-.322-.01-.482A7.556 7.556 0 0 0 18 1.75a7.317 7.317 0 0 1-2.12.586A3.736 3.736 0 0 0 17.502.273a7.354 7.354 0 0 1-2.345.905A3.673 3.673 0 0 0 12.463 0c-2.04 0-3.694 1.67-3.694 3.73 0 .292.032.577.096.85A10.45 10.45 0 0 1 1.253.683a3.746 3.746 0 0 0-.5 1.875c0 1.294.652 2.436 1.643 3.104a3.638 3.638 0 0 1-1.673-.466v.047A3.722 3.722 0 0 0 3.685 8.9a3.673 3.673 0 0 1-1.667.064 3.702 3.702 0 0 0 3.45 2.59A7.365 7.365 0 0 1 0 13.1a10.38 10.38 0 0 0 5.66 1.676" fill="#4D4545" fill-rule="evenodd"/></svg>
  - class: icon instagram
    href: https://www.instagram.com/gagesalzano/
    svg: <svg width="20" height="20" viewBox="0 0 16 16"><path d="M4.626.048c-.838.038-1.41.173-1.91.37a3.85 3.85 0 0 0-1.395.916 3.896 3.896 0 0 0-.908 1.408C.22 3.248.086 3.826.048 4.672.009 5.52 0 5.79 0 7.949s.01 2.43.048 3.277.17 1.424.365 1.93c.201.523.47.966.908 1.408.438.442.876.714 1.394.917.5.196 1.073.33 1.91.37.84.038 1.108.047 3.246.047 2.137 0 2.405-.01 3.245-.048.838-.038 1.41-.173 1.91-.37a3.857 3.857 0 0 0 1.394-.916c.438-.442.707-.885.908-1.408.195-.506.328-1.083.366-1.93.038-.847.047-1.118.047-3.277s-.009-2.43-.047-3.277c-.038-.846-.171-1.424-.366-1.93a3.901 3.901 0 0 0-.908-1.408 3.855 3.855 0 0 0-1.393-.917c-.501-.196-1.073-.33-1.911-.369C10.276.009 10.008 0 7.87 0 5.733 0 5.465.01 4.626.048m.064 14.371c-.767-.035-1.184-.164-1.461-.273a2.437 2.437 0 0 1-.905-.595 2.465 2.465 0 0 1-.589-.914c-.108-.28-.236-.7-.271-1.476-.038-.838-.046-1.09-.046-3.212 0-2.123.008-2.374.046-3.212.035-.775.163-1.196.271-1.476.143-.371.314-.636.589-.914.275-.278.537-.45.905-.595.277-.108.694-.238 1.461-.273.83-.039 1.08-.047 3.18-.047 2.102 0 2.351.008 3.181.047.767.035 1.184.165 1.462.273.367.144.63.317.905.595.275.278.445.543.588.914.108.28.236.701.271 1.476.038.838.046 1.09.046 3.212s-.008 2.374-.046 3.212c-.035.775-.163 1.196-.27 1.476a2.465 2.465 0 0 1-.59.914c-.275.278-.537.45-.904.595-.278.109-.695.238-1.462.273-.83.039-1.079.047-3.18.047-2.102 0-2.35-.008-3.18-.047m6.437-10.713a.95.95 0 0 0 .944.954.95.95 0 0 0 .945-.954.95.95 0 0 0-.945-.954.95.95 0 0 0-.944.954m-7.3 4.243c0 2.255 1.81 4.082 4.043 4.082 2.232 0 4.041-1.827 4.041-4.082 0-2.254-1.809-4.082-4.041-4.082S3.829 5.695 3.829 7.949m1.418 0c0-1.463 1.175-2.65 2.624-2.65s2.623 1.187 2.623 2.65c0 1.464-1.174 2.65-2.623 2.65-1.45 0-2.624-1.186-2.624-2.65" fill="#4D4545" fill-rule="evenodd"/></svg>

quotes:
  - quote: A good concept is like a good lasagna…
    source: There’s alotta layers to it.
    href:

  - quote: New York Design Agency, New York Brand Identity, Visual Design, Web Design, Graphic Design, Logo Designer New York
    source: Sorry, just trying to fit in some keywords to boost our rankings on Google.
    href:

  - quote: Sprinting, Huddling, Sketching, Concepting, Ideating, Circling back, Slow roasting, Jump roping, …
    source: We do it all.
    href:

  - quote: We’re highly proficient in Googling things…
    source: and we’re Feeling Lucky today, baby.
    href:

  - quote: How can we stop robots from taking our jobs?
    source: Make them sign-up for LinkedIn.
    href:

  - quote: It's about time websites stop just accepting cookies…
    source: …and start *enjoying* them.
    href:

  - quote: We don’t just design Web Apps…
    source: …we design Web Hors D’oeuvres.
    href:

  - quote: We're like the club sandwich of design studios…
    source: …all-around pretty good.
    href:

  - quote: We tried A/B testing this headline…
    source: …and you can C it didn’t work.
    href:

# Build settings
source: ./src
destination: ./dist
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer


# Collections
collections:
  projects:
    output: true

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: "project"